import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
// import profilePic from '../images/pic.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/icons'
import HireButton from '@/components/HireButton'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import ParticlesBackground from '@/components/ParticlesBackground'

export default function Home() {
  return (
    <>
      <Head>
        <title>Prashant</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center w-full min-h-screen dark:text-light'>
        <ParticlesBackground/>

        <Layout className='pt-0 sm:pt-8 md:pt-16'>
          {/* below div is for image and body text */}
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="Prashant " className='w-full h-auto lg:hidden 
                              md:inline-block md:w-full'
                priority
                sizes='(max-width: 768px) 100vw,
                  (max-width:1200px) 50vw,33vw'
              />
            </div>
            <div className='w-1/2 flex flex-col item-center self-center lg:w-full lg:text-center'>
              {/* below is for animated text */}
              {/* <span className={`s:180`}>An </span>Artist who makes<br className='sm:block hidden' />
            <span className="font">Arts by coding .</span> */}
              {/* <AnimatedText text="Turning Vision Into Reality With Code And Design."  */}
                      // <AnimatedText text="An Artist who makes Art by coding ." 
                      //   className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl' 
                      // />
              <AnimatedText
                text="An Artist who makes Art by coding."
                className="!text-6xl pb-1 !text-left xl:!text-5xl 
                  lg:!text-center lg:!text-6xl md:!text-5xl 
                  sm:!text-3xl text-transparent animated_text
                  dark:text-transparent"
               />

                    
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs' >
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              {/* for button */}
              <div className='mt-2 items-center self-start flex lg:self-center'>
                <Link href="/Prashant.pdf" target={"_blank"}
                  className='items-center bg-dark text-light rounded-lg 
                      p-2.5 px-6 flex text-lg font-semibold hover:bg-light
                      hover:text-dark border-2 border-solid border-transparent 
                      hover:border-dark dark:bg-light dark:text-dark 
                      hover:dark:text-light hover:dark:bg-dark 
                      hover:dark:border-light md:p-2 md:px-4 md:text-base' download={true}>
                      Resume <LinkArrow className={'w-6 ml-1'} /></Link>
                <Link href="mailto:prashantkry89@gmail.com" target={"_blank"} 
                  className='ml-4 text-lg capitalize text-dark underline dark:text-light
                    md:text-base'>Contact Me</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireButton />
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image src={lightBulb} alt='lightBulb' className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
